spring:
  cache:
    cache-names: USER_BY_USERNAME
  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    password: ${DB_PASSWORD}
    user: postgres
    url: ${DATASOURCE_URL}
    change-log: classpath:liquibase/changelog.yaml
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
      password: ${DB_PASSWORD}
      username: postgres
      jdbc-url: ${DATASOURCE_URL}
    url: ${DATASOURCE_URL}
    password: ${DB_PASSWORD}
    username: postgres
    driver-class-name: org.postgresql.Driver